name: 'Create housekeeping issues'

on:
  schedule:
  - cron:  '0 10 1 */2 *' # run every second month

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/issue-template-dependencies.md
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/issue-template-test-versions.md