name: 'Cross-BrowserÂ Test'
on:
  schedule:
    - cron:  '0 2 * * *' # UTC time

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  test-e2e:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        browser: [chrome, firefox, electron]
    container: # run in container to have specific versions of browsers available
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001 # see [firefox restriction](https://github.com/cypress-io/github-action#firefox)
      env:
        VUE_APP_BACKEND_TYPE: 'testVolatile'
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run build
    - run: npm run test:e2e:run:${{ matrix.browser }}
      name: End-To-End tests on ${{ matrix.browser }} w/ local backend
